# Generated by Django 5.0.4 on 2024-04-06 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='account_number',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='dedicated_virtual_account',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='ref_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50000),
        ),
        migrations.AddField(
            model_name='userdata',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50000),
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_notification',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_status',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=150, null=True, unique=True),
        ),
    ]
